const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",
  //user
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",

  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",

  //admin
  FETCH_GENDER_START: "FETCH_GENDER_START",
  FETCH_GENDER_SUCCESS: "FETCH_GENDER_SUCCESS",
  FETCH_GENDER_FAIL: "FETCH_GENDER_FAIL",

  //position
  FETCH_POSITION_SUCCESS: "FETCH_POSITION_SUCCESS",
  FETCH_POSITION_FAIL: "FETCH_POSITION_FAIL",

  //role
  FETCH_ROLE_SUCCESS: "FETCH_ROLE_SUCCESS:",
  FETCH_ROLE_FAIL: "FETCH_ROLE_FAIL",

  //create new user
  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_FAIL: "CREATE_USER_FAIL",

  //delete user

  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAIL: "DELETE_USER_FAIL",

  EDIT_USER_SUCCESS: "EDIT_USER_SUCCESS",
  EDIT_USER_FAIL: "EDIT_USER_FAIL",

  FETCH_ALL_USERS_SUCCESS: "FETCH_ALL_USERS_SUCCESS",
  FETCH_ALL_USERS_FAIL: "FETCH_ALL_USERS_FAIL",

  //topdoctor
  FETCH_TOP_DOCTORS_SUCCESS: "FETCH_TOP_DOCTORS_SUCCESS",
  FETCH_TOP_DOCTORS_FAIL: " FETCH_TOP_DOCTORS_FAIL",

  //getall doctor
  FETCH_ALL_DOCTORS_SUCCESS: "FETCH_ALL_DOCTORS_SUCCESS",
  FETCH_ALL_DOCTORS_FAIL: "FETCH_ALL_DOCTORS_FAIL",

  //save doctor
  SAVE_DETAIL_DOCTORS_SUCCESS: "SAVE_DETAIL_DOCTORS_SUCCESS",
  SAVE_DETAIL_DOCTORS_FAIL: "SAVE_DETAIL_DOCTORS_FAIL",


  //get doctorid
  FECTH__DETAIL_DOCTORS_SUCCESS: "FECTH__DETAIL_DOCTORS_SUCCESS",
  FECTH__DETAIL_DOCTORS_FAIL: "FECTH__DETAIL_DOCTORS_FAIL",
});

export default actionTypes;
